### ISSUE TITLE
generics branch no longer works on go1.18rc1

### ISSUE THREAD

**Issue by billinghamj** [deckarep/golang-set#79]
I realise it is not intended for use at this point, but thought it might be useful to bring to your attention.

The generics branch works great on go1.18beta1 & go1.18beta2

But on go1.18rc1, it has these errors:

```
# github.com/deckarep/golang-set
./set.go:169:17: any does not implement comparable
./set.go:172:37: any does not implement comparable
./threadsafe.go:230:43: any does not implement comparable
./threadsafe.go:232:55: any does not implement comparable
./threadsafe.go:235:24: any does not implement comparable
./threadsafe.go:237:44: any does not implement comparable
./threadsafe.go:238:26: any does not implement comparable
./threadsafe.go:249:63: any does not implement comparable
./threadsafe.go:255:72: any does not implement comparable
./threadsafe.go:256:24: any does not implement comparable
./threadsafe.go:256:24: too many errors
```

I think this is as a consequence of https://github.com/golang/go/issues/50646#ref-commit-360e1b8

I've had a good look at it, and made some adjustments which seem to resolve most of it. But I wasn't able to find a way to get `PowerSet` working

For `Pop`:

```go
func (s *threadUnsafeSet[T]) Pop() (v T, ok bool) {
	for item := range *s {
		delete(*s, item)
		return item, true
	}
	return
}
```

(Though this does require a change to the method signature - an alternative might be to introduce a new method and return the zero value on the old one, or to return a pointer)

Edit: For `CartesianProduct`, your intended code still seems to have the same problem

For `PowerSet`, the problem is that it won't allow `Set[Set[T]]` (Set[T] does not implement comparable), and the interface cannot be declared as comparable (interface is (or embeds) comparable)

Perhaps an alternative might be to return `[]Set[T]`(?)

**Comment by billinghamj** [comment]
Going through playing with some changes, for some of the tests, it seems there is no workaround to enable what they're trying to do

I've commented on the PR to flag that, as it seems odd to make this kind of code impossible to write

**Comment by billinghamj** [comment]
For now, I've released here without the problematic methods, as a workaround: https://github.com/billinghamj/golang-set

**Comment by deckarep** [comment]
Hey thanks for the vote of confidence on the new changes as well as the big report.

PowerSet was added sometime back for completion sake but I will admit that I don’t think it’s used all that much. I have recently considered removing it because I couldn’t find a great solution that was generics compatible.

Your investigation is appreciated and I’ll see what I can do in the coming days.

**Comment by billinghamj** [comment]
No problem 🙂 I'm very happy to pitch in with anything if that'd be helpful too 👌

**Comment by billinghamj** [comment]
@deckarep Now that 1.18 is out, do you think you'd be interested in releasing the generics branch, perhaps with the 2 problematic methods removed?

**Comment by deckarep** [comment]
@billinghamj  - sorry for the delay on this. I have finally got around to release a 2.0.0 tag using your changes to support the final release of Go 1.18.

Big thanks for sorting out the bug around `any` type not being `comparable`.

**Comment by billinghamj** [comment]
@deckarep btw, now that Go 1.20 is out, I think those methods could be added back :)
